### GET All Shipments
GET http://localhost:3000/api/shipment


























### GET Shipment By ID
GET http://localhost:3000/api/shipment/2


















### CREATE Shipment
POST http://localhost:3000/api/shipment
Content-Type: application/json

{
  "ship_date": "2026-01-17",
  "status": "In Transit",
  "tracking_number": "TH999888",
  "destination": "Chiang Rai"
}










### UPDATE Shipment
PUT http://localhost:3000/api/shipment/2
Content-Type: application/json

{
  "ship_date": "2026-01-18",
  "status": "Delivered",
  "tracking_number": "TH456123",
  "destination": "Phayao"
}












### DELETE Shipment
DELETE http://localhost:3000/api/shipment/3
